name: explore
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  easy_dynamic_theme: ^2.0.0
  flutter_plugin_android_lifecycle: ^2.0.2

  #Firebase
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_storage:
  image_picker_web: ^2.0.2
  #  cloud_firestore:


  #Google
  google_sign_in: ^5.0.1
  cloud_firestore:
  google_fonts: ^2.0.0

  #Social media launcher
  url_launcher:

  #UI
  auth_buttons: ^1.0.0
  flutter_signin_button: ^2.0.0

  #Email validator
  email_validator: '^1.0.6'

  file_picker: ^3.0.2+2

#  firebase: ^9.0.1
#  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  #draggable_scrollbar: 0.0.4

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf

  assets:
    - assets/images/
